/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.javezki;

import org.bukkit.plugin.java.JavaPlugin;

public class App {
    
    public static JavaPlugin plugin;

    public static JavaPlugin getJavaPlugin() {
        return plugin;
    }

    public static void setPlugin(final JavaPlugin plugin){
        App.plugin = plugin;

    }

    public String getGreeting() {
        return "Hello World";
    }


}
